#+TITLE: ECE 551-B Problems in Machine Learning
#+AUTHOR:Silas Curfman
#+DESCRIPTION: SPRING 2023 / Automatic Acoustic Anamoly Detection Iot/IIot
#+TEXT: Research notes for research project
#+TAGS: HRDWR SFTWR ML CODE
#+SEQ_TODO: NEXT(n) TODO(t) WAITING(w) SOMEDAY(s) | DONE(d) CANCELLED(c)
#+OPTIONS: toc:3 broken-links:mark

* PROJECT TRACKER

** PROJECT PROPOSAL
*** NEXT Purpose Questions [1/3]
- [-] Solving What Problem(s)? [1/1]
  - [X] [#1] Save Money $
Reduce number of unexpected days downtime and limit degree of damage due to uncaught catastrophic events such as: debris intake small, debris intake large, fibre / organic material wrapping or binding, cavitation initiation (impeller coating worn off), etc.
  - [X] [#2] Save Money $$
Provide real-time, non-control channel, degree of variance from baseline operation in form of relative 'grading' or 'scoring' of each pump present in a given station (group of pumps).  Higher pump id's would receive grade or score based on last known performance upon shutdown.  Prior to startup of station, pump scores are polled and depending on how many units need to be activated the choice of pump and sequence of start up order will be chosen on a highest score wins case / switch.  Baselining and grading would be unique to a given pump station.  Different pump station locations have different system characteristics that make comparing pumps across multiple stations unlikely.
  - [ ] Deliver report & presentation for UNM ECE-551
*** TODO Project Questions [2/13]
- [X] Q/A: ML / Detection vs Recogntion?
A:DETECTION ONLY
- [X] Q/A: Remote vs. On-site implementation?
A:REMOTE
- [ ]Q/A: Algorithms: SVM, NN?
should focus on locally runable algorithms, SVM?
- [ ] Q/A: Datasets: ToyADMOS, ToyAMOS2, DCASE, PRONOSTIA, ?

- [ ] Q/A: Processing Architecture: x86, ARM, FPGA, SoC, etc?

- [ ] Q/A: Sensors: ultrasonic vs. audible range? / air-gapped vs. surface mounted?

- [ ] Q/A: Intended budget level: affordable?

- [ ] Q/A: Utilize existing client network?

- [ ] Q/A: Utilize existing client control sys infrastructure?

- [ ] Q/A: Utilize existing power / electrical supply vs. mobile solution?

- [ ] Q/A: ML processing Real-Time vs Off-line // local vs. cloud?

- [ ] Q/A: Input data format (wav, mp3, fft, etc)

- [ ] Q/A: Output data format (text based logs, messages?)

- [ ] Q/A: Bandwidth limitations; microwave, radio, fiber, etc.

- [ ] Q/A: Working prototype or Proposed Design?

*** TODO ROADMAP
- [ ] Standard Report Outline (abstract, ... , citations)
- [ ] Abstract
- [ ] Index Terms
- [ ] Introduction (problem to solve, state of the art, available means)
- [ ] Theory (hardware, software, & algorithms)
- [ ] Methods and Materials (experiment)
- [ ] Results (output)
- [ ] Conculsion (did we solve a problem, future thoughts)
- [ ] References
- [ ] Present Final report in person / live presentation
  
** STATE OF THE ART

*** KEYWORDS:
:KEYWORDS:
acoustic anamoly detection, one class SVM, novelty detection, unsupervised anomaly detection, real-time, acoustic emission, ultrasonic, 
:END:
*** Search Results:

*** Academic Papers:
**** A Machine Learning Approach for locating Acoustic Emissions
**** Acoustic emmision used for detection of crack generation in propellers of turbine-pump units
**** The application of acoustic emission for detecting incipient cavitation and the best efficiency point of a 60kW centrifugal pump: case study
**** Machine-Learning-Based Methods for Acoustic Emission Testing: A Review
**** Acoustic Anomaly Detection in Additive Manufacturing with Long Short-Term Memory Neural Networks
**** Acoustic Anomaly Detection of Mechanical Failures in Noisy Real-Life Factory Environments
**** Validation of artificial neural networks to model the acoustic behavior of induction motors
**** A comparison between psychoacoustic parameters and condition indicators for macinery fault diagnosis using vibration signals
**** Psychoacoustic approach for cavitation detection in centrifugal pumps
**** Remote acoustic analysis for tool condition monitoring
**** A low engery FPGA platform for real-time event-based control
**** Several Approaches for Anomaly Detection From Sound
**** An FPGA Platform Proposal for Real-Time Acoustic Event Detection
**** FPGA Implementations of Support Vector Machine Using Ising Model for AI on Things
**** FPGA-Embedded Anomaly Detection System for Milling Process
**** A machine sound monitoring for predictive maintenance focusing on very low frequency band
**** Design and Implementation of Acoustic Sensing System for Online Early Fault Detection in Industrial Fans
**** FPGA based monitoring platform for condition monitoring in cylindrical grinding
**** The development of surface acoustic wave sensors (SAWs) for process monitoring
**** One class svm for [[https://www.researchgate.net/publication/265946573_One-Class_SVM_Based_Approach_for_Detecting_Anomalous_Audio_Events][link]]
**** Anomalous Sound Detection [[https://arxiv.org/pdf/2102.07820v1.pdf][link]]
**** Discussion of Features for Acoustic Anomaly [[https://www.researchgate.net/publication/365081524_Discussion_of_Features_for_Acoustic_Anomaly_Detection_under_Industrial_Disturbing_Noise_in_an_End-of-Line_Test_of_Geared_Motors][link]]


*** Potential Data Sets
**** MIMII Dataset: Sound Dataset for Malfunctioning Industrial Machine Investigation and Inspection
**** ToyADMOS dataset
**** ToyADMOS dataset 2
**** PRONOSTIA Bearing Dataset

*** Existing Kaggle, Jupyter Notebooks, GitHub Repo's

**** DCASE2020 Challenge Task 2 baseline variants :KAGGLE:
**** Federated Learning for Autoencoder-based Anomaly Detection in the Industrial Iot  :GITHUB:
**** Self-Supervised Acoustic Anomaly Detection... :GITHUB:
https://github.com/Armanfard-Lab/AADCL

**** Unsupervised Anomaly Detection...
https://www.kaggle.com/code/victorambonati/unsupervised-anomaly-detection


*** Commercial, Industry Links:
**** Webinar: Automated Acoustic...
https://www.youtube.com/watch?v=-6B_XsEN2Q4
**** YT: One class SVM detection...
https://www.youtube.com/watch?v=0dngOGhv5Mc
**** MSFT: Hybrid Model Approach for Real-Time Acoustic Anomaly Detection using Time-Series
**** INTEL: Intel Labs uses AI and Audio Anomaly Detection to Prevent Semiconductor Manufacturing Malfunctions
**** UE SYSTEMS INC: Ultra-Trak 750 ultrasonic amplitude sensor
**** GFAI-TECH: 2D Outdoor Measurement, Acoustic Cameras
**** NATIONAL THERMAL POWER CORPORATION: Ultrasonic, A new method for condition monitoring
**** NASA: Preferred practice for Design & Test / Acoustic Noise (flight data microphones)
**** SICK SENSOR INTELLIGENCE: Real-Time Condition Monitoring Sensor For Industrial Machinery (new MPB10 multiphysics sensor)
**** MRO MAGAZINE: Complete List of Condition Monitoring Techniques
**** PCB PIEZOELECTRONICS (AMPHENOL): Microphones for Aerospace/Acoustic Applications
**** ARTISS-MARPOSS: Acoustic Emission Sensors (AE-C & AE-C micro)
**** IBM / USPTO Patent: ACOUSTICS BASED ANOMALY DETECTION IN MACHINE ROOMS (date:2018-02-13, patent no:9,892,744)

** INSTRUCTOR QUESTIONS
*** TODO 

